#====================Desired Capabilities=====================#
appActivity=
appPackage=
platformName=Android Emulator

platformVersion = 11
deviceName = 52001219533f8677
app=
newCommandTimeout = 1800
automationName = uiautomator2
endpoint = http://0.0.0.0:4723/wd/hub
Runner=Local
systemPort=8201
#========<playstore, staging>==================
buildType=playstore
playstorepkg=com.android.vending
playstoreActivity=com.google.android.finsky.activities.MainActivity



